
CREATE TABLE COUNTRY (
		COUNTRY_ID NUMBER(20,0) NOT NULL,
		CODE CHAR (2 CHAR) NOT NULL,
		CREATED_ON TIMESTAMP NOT NULL,
		MODIFIED_ON TIMESTAMP);

ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( COUNTRY_ID );


CREATE TABLE PERSON ( 
		PERSON_ID NUMBER (20,0) NOT NULL, 
		CREATED_ON TIMESTAMP NOT NULL,
		MODIFIED_ON TIMESTAMP);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY ( PERSON_ID );


CREATE TABLE ADDRESS ( 
		ADDRESS_ID NUMBER (20,0) NOT NULL,
		COUNTRY_ID NUMBER (20), 
		STREET VARCHAR2 (100 CHAR),   
		DISTRICT_NAME VARCHAR2 (100 CHAR), 
		POST_CODE VARCHAR2 (50 CHAR), 
		CITY VARCHAR2 (100 CHAR),   
		ADDRESS_TYPE VARCHAR2 (50 CHAR), 
		CREATED_ON TIMESTAMP NOT NULL,  
		MODIFIED_ON TIMESTAMP);

ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( ADDRESS_ID );

ALTER TABLE ADDRESS 
	ADD CONSTRAINT ADDRESS_COUNTRY_FK FOREIGN KEY ( COUNTRY_ID ) 
	REFERENCES COUNTRY ( COUNTRY_ID ) 
	ON DELETE CASCADE;

CREATE TABLE PERSON_ADDRESS (
		PERSON_ADDRESS_ID NUMBER(20,0) NOT NULL,
		ADDRESS_ID NUMBER(20,0) NOT NULL,
		PERSON_ID NUMBER(20,0) NOT NULL, 
		CREATED_ON TIMESTAMP NOT NULL,
		MODIFIED_ON TIMESTAMP);
	
ALTER TABLE PERSON_ADDRESS ADD CONSTRAINT PERSON_ADDRESS_PK PRIMARY KEY ( PERSON_ADDRESS_ID );

ALTER TABLE PERSON_ADDRESS
	ADD CONSTRAINT PERSON_ADDRESS_ADDRESS_FK FOREIGN KEY ( ADDRESS_ID )
	REFERENCES ADDRESS ( ADDRESS_ID )
	ON DELETE CASCADE;

ALTER TABLE PERSON_ADDRESS
	ADD CONSTRAINT PERSON_ADDRESS_PERSON_FK FOREIGN KEY ( PERSON_ID )
	REFERENCES PERSON ( PERSON_ID )
	ON DELETE CASCADE;
 

CREATE TABLE BIRTH (
		BIRTH_ID NUMBER (20,0) NOT NULL, 
		BIRTH_DATE VARCHAR2(10 CHAR), 
		BIRTH_CITY VARCHAR2 (250 CHAR),  
		COUNTRY_ID NUMBER (20,0),
		CREATED_ON TIMESTAMP NOT NULL,
		MODIFIED_ON TIMESTAMP);

ALTER TABLE BIRTH ADD CONSTRAINT BIRTH_PK PRIMARY KEY ( BIRTH_ID );

ALTER TABLE BIRTH 
	ADD CONSTRAINT BIRTH_COUNTRY_FK FOREIGN KEY ( COUNTRY_ID )
	REFERENCES COUNTRY ( COUNTRY_ID )
	ON DELETE CASCADE;

CREATE SEQUENCE COUNTRY_SEQ NOCYCLE NOCACHE START WITH 1 NOMAXVALUE';
CREATE SEQUENCE PERSON_SEQ NOCYCLE NOCACHE START WITH 1 NOMAXVALUE';
CREATE SEQUENCE ADDRESS_SEQ NOCYCLE NOCACHE START WITH 1 NOMAXVALUE';
CREATE SEQUENCE PERSON_ADDRESS_SEQ NOCYCLE NOCACHE START WITH 1 NOMAXVALUE';
CREATE SEQUENCE BIRTH_SEQ NOCYCLE NOCACHE START WITH 1 NOMAXVALUE';